#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QObject>
#include <QtQml/qqmlregistration.h>
#include <QString>
#include <QtGlobal>
#include <QProcess>
#include <QtCore>
#include <QLocale>
#include <QIcon>
#ifdef Q_OS_WINDOWS
#define _WIN32_DCOM
#include <windows.h>
#include <tlhelp32.h>
#include <tchar.h>
#include <comdef.h>
#include <Wbemidl.h>
#pragma comment(lib, "wbemuuid.lib")
#endif //Q_OS_WINDOWS
